eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
  instance:
    prefer-ip-address: true
info:
  app:
    name: "productservice using config server"
    description: "Product Service"
    version: "1.0"
